# Generated by Django 3.2.8 on 2023-01-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0130_employee_pf_eligibility'),
        ('provident_fund', '0002_monthlyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pf_account', to='employee.employee'),
        ),
    ]
