# Generated by Django 3.2.8 on 2023-12-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provident_fund', '0003_alter_account_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyentry',
            options={'verbose_name': 'Monthly Entry', 'verbose_name_plural': 'Monthly Entries'},
        ),
    ]
