# Generated by Django 3.2 on 2021-04-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='payscale',
            old_name='user',
            new_name='created_by',
        ),
    ]
