# Generated by Django 3.2 on 2021-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210501_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='payscale',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=11),
            preserve_default=False,
        ),
    ]
