# Generated by Django 3.2 on 2021-06-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_publicholiday_publicholidaydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholidaydate',
            name='public_holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holiday', to='settings.publicholiday'),
        ),
    ]
