# Generated by Django 3.2.5 on 2021-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_publicholidaydate_public_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payscale',
            name='basic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='house_allowance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='increment_rate',
            field=models.FloatField(help_text='In percentage'),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='medical_allowance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='net_payable',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payscale',
            name='travel_allowance',
            field=models.FloatField(),
        ),
    ]
