# Generated by Django 3.2.5 on 2021-07-07 16:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='footer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='header',
            field=tinymce.models.HTMLField(),
        ),
    ]
