# Generated by Django 3.2.5 on 2021-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20210707_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='title',
            field=models.CharField(default='dd', max_length=250),
            preserve_default=False,
        ),
    ]
