# Generated by Django 3.2.8 on 2023-04-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_employeefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFAQView',
            fields=[
            ],
            options={
                'permissions': (('employee_faqs_view', 'Can Employee FAQ list view.'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settings.employeefaq',),
        ),
    ]
