# Generated by Django 3.2.8 on 2023-04-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_employeefaqview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefaqview',
            options={'permissions': (('employee_faqs_view', 'Can Employee FAQ list view.'),), 'verbose_name_plural': 'FAQ List'},
        ),
    ]
