# Generated by Django 3.2.8 on 2023-04-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_alter_employeefaq_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeFAQView',
        ),
    ]
