# Generated by Django 3.2.8 on 2023-04-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_delete_employeefaqview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeFaq',
        ),
    ]
