# Generated by Django 3.2.8 on 2023-05-11 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 16, 53, 48, 221092)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 16, 53, 57, 493698)),
            preserve_default=False,
        ),
    ]
