# Generated by Django 3.2.8 on 2023-05-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_auto_20230511_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='rank',
            field=models.SmallIntegerField(default=0),
        ),
    ]
