# Generated by Django 3.2.8 on 2023-12-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_alter_announcement_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefoodallowance',
            options={'verbose_name': 'Employee Food Allowance', 'verbose_name_plural': 'Employee Food Allowances'},
        ),
    ]
