# Generated by Django 3.2.8 on 2024-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_remove_emailannouncement_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailannouncement',
            name='attachments',
        ),
        migrations.AddField(
            model_name='emailannouncement',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
