# Generated by Django 3.2.8 on 2024-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_auto_20240208_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailannouncement',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/'),
        ),
    ]
