# Generated by Django 3.2.8 on 2024-02-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0032_emailannouncement_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailannouncement',
            name='attachments',
        ),
        migrations.AlterField(
            model_name='emailannouncement',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.announcement'),
        ),
        migrations.CreateModel(
            name='EmailAnnouncementAttatchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_emailannouncementattatchment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fileattatchment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.emailannouncement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
