# Generated by Django 3.2.8 on 2024-02-08 17:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_emailannouncementattatchment_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailannouncement',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
