# Generated by Django 3.2.8 on 2024-02-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_alter_emailannouncement_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailannouncementattatchment',
            old_name='fileattatchment',
            new_name='email_announcement',
        ),
    ]
