# Generated by Django 3.2.8 on 2024-03-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='allow_decimal',
            field=models.BooleanField(default=False),
        ),
    ]
