# Generated by Django 3.2.5 on 2021-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0031_rename_can_open_after_candidateassessment_can_start_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
