# Generated by Django 3.2.5 on 2021-08-03 14:36

from django.db import migrations, models
import job_board.models.candidate


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0032_job_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to=job_board.models.candidate.candidate_email_path),
        ),
    ]
