# Generated by Django 3.2.5 on 2021-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0033_auto_20210803_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejob',
            name='merit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobadditionalfield',
            name='validation_regx',
            field=models.CharField(default='(.*)', max_length=255),
        ),
    ]
