# Generated by Django 3.2.5 on 2021-08-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0034_auto_20210804_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateassessment',
            name='candidate_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_assessment', to='job_board.candidatejob'),
        ),
    ]
