# Generated by Django 3.2.5 on 2021-08-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0035_alter_candidateassessment_candidate_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='additional_requirement',
            new_name='additional_requirements',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='educational_requirement',
            new_name='educational_requirements',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='experience_requirements',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_responsibility',
            new_name='job_responsibilities',
        ),
    ]
