# Generated by Django 3.2.6 on 2021-08-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0040_jobcontext_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='additional_requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='compensation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='educational_requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_context',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_responsibilities',
        ),
    ]
