# Generated by Django 3.2.6 on 2021-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0041_auto_20210827_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
