# Generated by Django 3.2.6 on 2021-08-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0042_job_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontext',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_contexts', to='job_board.job'),
        ),
        migrations.AlterField(
            model_name='jobcontext',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
