# Generated by Django 3.2.8 on 2021-10-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0045_smspromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspromotion',
            name='sms_body',
            field=models.TextField(help_text='{full_name}=> Candidate Full Name, {candidate_job} => Candidate Job'),
        ),
    ]
