# Generated by Django 3.2.8 on 2021-11-17 07:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_board', '0046_alter_smspromotion_sms_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateassessment',
            name='updated_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_board_candidateassessment_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
