# Generated by Django 3.2.8 on 2021-11-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0047_candidateassessment_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateassessment',
            name='updated_by',
        ),
    ]
