# Generated by Django 3.2.8 on 2021-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0049_candidateassessmentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateassessmentreview',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
