# Generated by Django 3.2.8 on 2021-11-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0050_candidateassessmentreview_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateassessmentreview',
            name='score',
        ),
    ]
