# Generated by Django 3.2.8 on 2021-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0051_remove_candidateassessmentreview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
