# Generated by Django 4.0 on 2022-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0054_alter_assessment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateassessment',
            name='candidate_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
