# Generated by Django 3.2.8 on 2023-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0055_candidateassessment_candidate_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ('-order_by',)},
        ),
        migrations.AddField(
            model_name='assessment',
            name='order_by',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
