# Generated by Django 3.2.8 on 2023-10-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0057_candidate_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateassessment',
            options={'permissions': [('access_candidate_evaluation_url', "Can access candidate's evaluation url")]},
        ),
    ]
