# Generated by Django 3.2.8 on 2023-12-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0058_alter_candidateassessment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateassessment',
            options={'permissions': [('access_candidate_evaluation_url', "Can access candidate's evaluation url")], 'verbose_name': 'Candidate Assessment', 'verbose_name_plural': 'Candidate Assessments'},
        ),
    ]
