# Generated by Django 3.2.8 on 2024-02-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0060_jobvivatimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='jobvivatimeslot',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_board.candidate'),
        ),
        migrations.AlterField(
            model_name='jobvivatimeslot',
            name='duration',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='jobvivatimeslot',
            name='end_time',
            field=models.TimeField(editable=False),
        ),
    ]
