# Generated by Django 3.2.8 on 2024-02-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0061_auto_20240223_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvivatimeslot',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='jobvivatimeslot',
            name='job_post',
        ),
        migrations.AddField(
            model_name='jobvivatimeslot',
            name='viva_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job_board.vivaconfig'),
        ),
    ]
