# Generated by Django 3.2.8 on 2024-02-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0062_auto_20240223_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvivatimeslot',
            old_name='viva_config',
            new_name='job_post',
        ),
    ]
