# Generated by Django 3.2.8 on 2024-02-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0063_rename_viva_config_jobvivatimeslot_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivaconfig',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.job'),
        ),
    ]
