# Generated by Django 3.2.8 on 2024-02-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0064_alter_vivaconfig_job_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobvivatimeslot',
            options={'verbose_name': 'Booked Viva Slot for Candidates'},
        ),
    ]
