# Generated by Django 3.2.8 on 2024-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0065_alter_jobvivatimeslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vivaconfig',
            options={'verbose_name': 'Total Viva Slots'},
        ),
    ]
