# Generated by Django 3.2.8 on 2024-03-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0066_alter_vivaconfig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobvivatimeslot',
            options={'verbose_name': 'Booked Viva Slot for Candidate'},
        ),
        migrations.AlterModelOptions(
            name='vivaconfig',
            options={'verbose_name': 'Total Viva Slot'},
        ),
        migrations.CreateModel(
            name='ExcludedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('viva_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.vivaconfig')),
            ],
        ),
    ]
