# Generated by Django 3.2.8 on 2024-03-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0061_candidateemail_by_default'),
        ('job_board', '0067_auto_20240308_1254'),
    ]

    operations = [
    ]
