# Generated by Django 4.0.2 on 2022-03-29 20:26

import config.model.HTMLField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0020_client_logo_client_show_in_web_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('banner_image', models.ImageField(upload_to='')),
                ('feature_image', models.ImageField(upload_to='')),
                ('feature', config.model.HTMLField.HTMLField()),
                ('clients', models.ManyToManyField(to='project_management.Client')),
                ('technologies', models.ManyToManyField(to='project_management.Technology')),
            ],
        ),
    ]
