# Generated by Django 4.0.2 on 2022-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
