# Generated by Django 4.0.2 on 2022-03-31 15:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature',
            field=tinymce.models.HTMLField(),
        ),
    ]
