# Generated by Django 3.2.8 on 2023-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blog_tag_category_blogtag_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=None, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time_minute',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
