# Generated by Django 3.2.8 on 2024-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20240112_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontextimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
    ]
