# Generated by Django 3.2.8 on 2024-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_blogcontextimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_context_images'),
        ),
        migrations.DeleteModel(
            name='BlogContextImage',
        ),
    ]
