# Generated by Django 3.2.8 on 2024-01-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_blogcontextimage'),
        ('website', '0011_auto_20240115_1601'),
    ]

    operations = [
    ]
