# Generated by Django 3.2.8 on 2024-01-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_auto_20240115_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="blog_video"),
        ),
        migrations.AddField(
            model_name="blogcontext",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="blog_context_videos"
            ),
        ),
    ]
