# Generated by Django 3.2.8 on 2024-01-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_merge_0009_blogcontextimage_0011_auto_20240115_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContextImage',
        ),
    ]
