# Generated by Django 3.2.8 on 2024-01-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20240115_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_approve', 'Can Approve')]},
        ),
    ]
