# Generated by Django 3.2.8 on 2024-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='website.Category'),
        ),
    ]
