# Generated by Django 3.2.8 on 2024-01-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_approve', 'Can Approve'), ('can_view_all', 'Can View All Employees Blog'), ('can_change_after_approve', 'Can Change After Approve')]},
        ),
    ]
