# Generated by Django 3.2.8 on 2024-01-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_delete_blogcontextimage'),
        ('website', '0022_alter_blogcomment_blog'),
    ]

    operations = [
    ]
