# Generated by Django 3.2.8 on 2024-04-03 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0139_client_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0027_auto_20240402_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='technologies',
        ),
        migrations.CreateModel(
            name='ServiceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_servicetechnology_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.service')),
                ('technologies', models.ManyToManyField(to='project_management.Technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
