# Generated by Django 3.2.8 on 2024-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_ourjourney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourjourney',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceprocess',
            name='description',
            field=models.TextField(),
        ),
    ]
