# Generated by Django 3.2.8 on 2024-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20240403_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
    ]
