# Generated by Django 3.2.8 on 2024-05-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_blog_is_featured'),
        ('website', '0036_alter_blog_image'),
    ]

    operations = [
    ]
