# Generated by Django 3.2.8 on 2024-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0145_merge_20240522_1226'),
        ('website', '0037_merge_0026_blog_is_featured_0036_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('technology', models.ManyToManyField(to='project_management.Technology')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='industry',
            field=models.ManyToManyField(to='website.Industry'),
        ),
    ]
