# Generated by Django 3.2.8 on 2024-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20240522_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
