# Generated by Django 3.2 on 2021-04-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='projecthours',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='created_by',
        ),
    ]
