# Generated by Django 3.2 on 2021-04-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
        ('project_management', '0004_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projecthour',
            name='project',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='projecthour',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'manager': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
