# Generated by Django 3.2 on 2021-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_auto_20210501_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthour',
            name='payable',
            field=models.BooleanField(default=True),
        ),
    ]
