# Generated by Django 3.2.5 on 2021-07-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0067_auto_20210707_2024'),
        ('project_management', '0007_projecthour_payable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProjectHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.FloatField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_employeeprojecthour_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.employee')),
                ('project_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.projecthour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
