# Generated by Django 3.2.5 on 2021-07-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0068_auto_20210707_2229'),
        ('project_management', '0008_employeeprojecthour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprojecthour',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'manager': False}, on_delete=django.db.models.deletion.RESTRICT, to='employee.employee'),
        ),
    ]
