# Generated by Django 3.2.5 on 2021-07-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_alter_employeeprojecthour_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprojecthour',
            options={'permissions': [('change_recent_activity', 'Can change if inserted recently (3days)')]},
        ),
    ]
