# Generated by Django 4.0.2 on 2022-03-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_durationunit_projectresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='durationunit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='duration_unit',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.durationunit'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='project',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
