# Generated by Django 4.0.2 on 2022-03-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0097_alter_employee_tax_info'),
        ('project_management', '0015_durationunit_active_projectresource_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='employees',
            field=models.ManyToManyField(limit_choices_to={'active': True, 'manager': False}, related_name='employees', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'active': True, 'manager': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
