# Generated by Django 4.0.2 on 2022-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0016_alter_projectresource_employees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='durationunit',
            old_name='duration',
            new_name='description',
        ),
        migrations.AddField(
            model_name='durationunit',
            name='duration_in_hour',
            field=models.FloatField(default=1),
        ),
    ]
