# Generated by Django 4.0.2 on 2022-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0017_rename_duration_durationunit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='duration_hour',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='duration',
            field=models.FloatField(help_text='Estimated Project End Duration', max_length=200),
        ),
    ]
