# Generated by Django 4.0.2 on 2022-03-14 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0097_alter_employee_tax_info'),
        ('project_management', '0018_projectresource_duration_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresource',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='duration_hour',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='duration_unit',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='employees',
        ),
        migrations.CreateModel(
            name='ProjectResourceEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField(help_text='Estimated Project End Duration', max_length=200)),
                ('duration_hour', models.FloatField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('duration_unit', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.durationunit')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('project_resource', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.projectresource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
