# Generated by Django 4.0.2 on 2022-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0020_client_logo_client_show_in_web_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_in_website',
            field=models.BooleanField(default=False),
        ),
    ]
