# Generated by Django 4.0.2 on 2022-03-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0021_project_show_in_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
