# Generated by Django 4.0.2 on 2022-03-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0022_projectcontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttechnology',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
            preserve_default=False,
        ),
    ]
