# Generated by Django 4.0.2 on 2022-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0024_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
