# Generated by Django 4.0.2 on 2022-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0027_project_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresourceemployee',
            name='hour',
            field=models.FloatField(default=True, help_text='Estimated hours for each week', max_length=200, null=True),
        ),
    ]
