# Generated by Django 4.0.2 on 2022-09-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0104_employee_show_in_web'),
        ('project_management', '0032_project_in_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='on_boarded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
