# Generated by Django 4.1.3 on 2022-11-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0033_project_on_boarded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='description',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
    ]
