# Generated by Django 4.0.2 on 2022-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0035_alter_projecthour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthour',
            name='forcast',
            field=models.CharField(choices=[('increase', '⬆ Increase'), ('decrease', '⬇ Decrease'), ('same', '✅ Same'), ('confused', '😕 Confused')], default='same', max_length=40),
        ),
    ]
