# Generated by Django 4.0.2 on 2022-11-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0037_alter_projecthour_forcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='forcast',
            field=models.CharField(choices=[('increase', '⬆ Increase'), ('decrease', '⬇ Decrease'), ('same', '✅ Same'), ('confused', '😕 Confused')], max_length=40),
        ),
    ]
