# Generated by Django 4.1.4 on 2022-12-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0040_projectfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFeedback',
        ),
    ]
