# Generated by Django 4.1.4 on 2022-12-22 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0043_projecttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='feedback_week',
            field=models.DateField(default=datetime.date(2022, 12, 22)),
            preserve_default=False,
        ),
    ]
