# Generated by Django 4.1.4 on 2022-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0044_clientfeedback_feedback_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='feedback_week',
            field=models.DateField(null=True),
        ),
    ]
