# Generated by Django 4.1.4 on 2022-12-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0045_alter_clientfeedback_feedback_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttoken',
            name='project',
            field=models.OneToOneField(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
