# Generated by Django 3.2.8 on 2023-01-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0048_alter_projecttoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'permissions': (('can_see_client_feedback_admin', 'Can see Client Feedback admin'),)},
        ),
    ]
