# Generated by Django 3.2.8 on 2023-01-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0124_alter_employeefeedback_options'),
        ('project_management', '0049_alter_clientfeedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprojecthour',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, to='employee.employee'),
        ),
    ]
