# Generated by Django 3.2.8 on 2023-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0050_alter_employeeprojecthour_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthour',
            name='hour_type',
            field=models.CharField(choices=[('project', 'Project Hour'), ('bonus', 'Bonus Project Hour')], default='project', max_length=40, verbose_name='Project Hour Type'),
        ),
    ]
