# Generated by Django 3.2.8 on 2023-01-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0051_projecthour_hour_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthour',
            options={'permissions': [('show_all_hours', 'Can show all hours just like admin'), ('select_hour_type', 'Can select Project Hour type')]},
        ),
    ]
