# Generated by Django 3.2.8 on 2023-01-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0052_alter_projecthour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprojecthour',
            options={'permissions': [('change_recent_activity', 'Can change if inserted recently (3days)'), ('see_all_employee_hour', 'Can see all emploployee project hour')]},
        ),
    ]
