# Generated by Django 3.2.8 on 2023-02-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0130_employee_pf_eligibility'),
        ('project_management', '0053_alter_employeeprojecthour_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming_convention', models.FloatField()),
                ('code_reusability', models.FloatField()),
                ('oop_principal', models.FloatField()),
                ('design_pattern', models.FloatField()),
                ('standard_git_commit', models.FloatField()),
                ('avg_rating', models.FloatField()),
                ('comment', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
            ],
        ),
    ]
