# Generated by Django 3.2.8 on 2023-02-02 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0130_employee_pf_eligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0053_alter_employeeprojecthour_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProjectUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.FloatField()),
                ('update', models.TextField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_dailyprojectupdate_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='dailyprojectupdate_employee', to='employee.employee')),
                ('manager', models.ForeignKey(limit_choices_to={'active': True, 'manager': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='dailyprojectupdate_manager', to='employee.employee')),
                ('project', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, to='project_management.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
