# Generated by Django 3.2.8 on 2023-02-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0054_dailyprojectupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdate',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')]},
        ),
    ]
