# Generated by Django 3.2.8 on 2023-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0055_auto_20230202_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='for_first_quarter',
            field=models.BooleanField(default=True),
        ),
    ]
