# Generated by Django 3.2.8 on 2023-02-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0055_alter_dailyprojectupdate_options'),
        ('project_management', '0056_codereview_for_first_quarter'),
    ]

    operations = [
    ]
