# Generated by Django 3.2.8 on 2023-02-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0057_merge_20230203_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprojectupdate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
    ]
