# Generated by Django 3.2.8 on 2023-02-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0130_employee_pf_eligibility'),
        ('project_management', '0058_dailyprojectupdate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='project',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
