# Generated by Django 3.2.8 on 2023-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0059_auto_20230203_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='hours',
            field=models.FloatField(default=0.0),
        ),
    ]
