# Generated by Django 3.2.8 on 2023-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0061_remove_dailyprojectupdate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprojectupdate',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '✔ Approved')], default='pending', max_length=20),
        ),
    ]
