# Generated by Django 3.2.8 on 2023-02-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0063_codereviewemployeefeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codereview',
            options={'permissions': (('can_give_code_review', 'Can give code review'),)},
        ),
    ]
