# Generated by Django 3.2.8 on 2023-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0064_alter_codereview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthour',
            name='forcast',
            field=models.CharField(blank=True, choices=[('increase', '✔ Increase'), ('decrease', '⌛ Decrease'), ('same', '⌛ Same'), ('confused', '😕 Confused')], max_length=40, null=True, verbose_name='Forecast next week hours'),
        ),
    ]
