# Generated by Django 3.2.8 on 2023-03-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0139_config'),
        ('project_management', '0065_alter_projecthour_forcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'active': True, 'manager': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mange', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='employee.employee'),
        ),
    ]
