# Generated by Django 3.2.8 on 2023-03-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0139_config'),
        ('project_management', '0066_auto_20230303_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
