# Generated by Django 3.2.8 on 2023-02-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0067_auto_20230228_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyProjectUpdateGroupByEmployee',
        ),
        migrations.CreateModel(
            name='DailyProjectUpdateGroupByEmployee',
            fields=[
                ('dailyprojectupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project_management.dailyprojectupdate')),
            ],
            options={
                'permissions': [('see_all_employee_update', 'Can see all daily update')],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
    ]
