# Generated by Django 3.2.8 on 2023-03-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0139_config'),
        ('project_management', '0067_alter_codereview_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True, 'manager': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mange', to='employee.employee'),
        ),
    ]
