# Generated by Django 3.2.8 on 2023-02-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0068_auto_20230228_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyProjectUpdateGroupByEmployee',
        ),
        migrations.CreateModel(
            name='DailyProjectUpdateGroupByEmployee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
    ]
