# Generated by Django 3.2.8 on 2023-03-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0069_auto_20230228_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyemployee',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')]},
        ),
    ]
