# Generated by Django 3.2.8 on 2023-03-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0068_alter_codereview_manager'),
        ('project_management', '0070_alter_dailyprojectupdategroupbyemployee_options'),
    ]

    operations = [
    ]
