# Generated by Django 3.2.8 on 2023-03-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0071_merge_20230309_1949'),
        ('project_management', '0071_merge_20230309_2012'),
    ]

    operations = [
    ]
