# Generated by Django 3.2.8 on 2023-03-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0072_merge_20230313_1430'),
        ('project_management', '0072_merge_20230313_1536'),
    ]

    operations = [
    ]
