# Generated by Django 3.2.8 on 2023-03-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0072_merge_20230313_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailypProjectUpdateGroupByProject',
            fields=[
            ],
            options={
                'permissions': [('see_all_employee_update', 'Can see all daily update')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
    ]
