# Generated by Django 3.2.8 on 2023-03-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0074_alter_dailyprojectupdate_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailypProjectUpdateGroupByProject',
        ),
        migrations.CreateModel(
            name='DailyProjectUpdateGroupByManager',
            fields=[
            ],
            options={
                'permissions': [('see_all_employee_update', 'Can see all daily update')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
        migrations.CreateModel(
            name='DailyProjectUpdateGroupByProject',
            fields=[
            ],
            options={
                'permissions': [('see_all_employee_update', 'Can see all daily update')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.dailyprojectupdate',),
        ),
    ]
