# Generated by Django 3.2.8 on 2023-03-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0073_merge_20230315_1221'),
        ('project_management', '0075_auto_20230314_1927'),
    ]

    operations = [
    ]
