# Generated by Django 3.2.8 on 2023-03-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0076_merge_20230315_1602'),
        ('project_management', '0076_merge_20230315_2023'),
    ]

    operations = [
    ]
