# Generated by Django 3.2.8 on 2023-03-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0077_merge_20230316_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyemployee',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'G By Emp', 'verbose_name_plural': 'G By Emp'},
        ),
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbymanager',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'G By Manager', 'verbose_name_plural': 'G By Manager'},
        ),
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyproject',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'G By Project', 'verbose_name_plural': 'G By Project'},
        ),
    ]
