# Generated by Django 3.2.8 on 2023-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0078_auto_20230321_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthour',
            options={'permissions': [('show_all_hours', 'Can show all hours just like admin'), ('select_hour_type', 'Can select Project Hour type'), ('weekly_project_hours_approve', 'Can approved and give feedback from CTO')], 'verbose_name_plural': 'Weekly Project Hours'},
        ),
        migrations.AlterField(
            model_name='projecthour',
            name='cto_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
