# Generated by Django 3.2.8 on 2023-03-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0079_auto_20230321_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthour',
            name='approved',
        ),
    ]
