# Generated by Django 3.2.8 on 2023-03-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0080_remove_projecthour_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthour',
            name='cto_feedback',
        ),
    ]
