# Generated by Django 3.2.8 on 2023-03-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0078_auto_20230317_2131'),
        ('project_management', '0081_remove_projecthour_cto_feedback'),
    ]

    operations = [
    ]
