# Generated by Django 3.2.8 on 2023-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0081_remove_projecthour_cto_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthour',
            name='approved_by_cto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecthour',
            name='cto_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
