# Generated by Django 3.2.8 on 2023-03-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0082_auto_20230321_1823'),
        ('project_management', '0082_merge_20230322_1311'),
    ]

    operations = [
    ]
