# Generated by Django 3.2.8 on 2023-03-23 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0083_merge_20230322_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyemployee',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'Group By Employee', 'verbose_name_plural': 'Group By Employee'},
        ),
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbymanager',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'Group By Manager', 'verbose_name_plural': 'Group By Manager'},
        ),
        migrations.AlterModelOptions(
            name='dailyprojectupdategroupbyproject',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'Group By Project', 'verbose_name_plural': 'Group By Project'},
        ),
        migrations.CreateModel(
            name='DailyProjectUpdateAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/daily_update/%y/%m', verbose_name='Document')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_dailyprojectupdateattachment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('daily_project_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.dailyprojectupdate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
