# Generated by Django 3.2.8 on 2023-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0085_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='extra_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
