# Generated by Django 3.2.8 on 2023-03-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0144_employee_need_cto'),
        ('project_management', '0086_projectdocument_extra_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprojecthour',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_project_hours', to='employee.employee'),
        ),
    ]
