# Generated by Django 3.2.8 on 2023-03-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0144_employee_need_cto'),
        ('project_management', '0087_alter_employeeprojecthour_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='review_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeprojecthour',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, to='employee.employee'),
        ),
    ]
