# Generated by Django 3.2.8 on 2023-03-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0088_auto_20230331_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='review_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
