# Generated by Django 3.2.8 on 2023-03-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0089_alter_codereview_review_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='review_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
