# Generated by Django 3.2.8 on 2023-04-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0091_alter_codereview_review_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProjectUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours', models.FloatField(default=0.0)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_dailyprojectupdatehistory_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('daily_project_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.dailyprojectupdate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
