# Generated by Django 3.2.8 on 2023-04-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0092_dailyprojectupdatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdatehistory',
            name='daily_project_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='project_management.dailyprojectupdate'),
        ),
    ]
