# Generated by Django 3.2.8 on 2023-04-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0094_employeefaq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeFaq',
        ),
    ]
