# Generated by Django 3.2.8 on 2023-04-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0095_delete_employeefaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprojectupdatehistory',
            old_name='daily_project_update',
            new_name='daily_project_update_hours',
        ),
        migrations.RemoveField(
            model_name='dailyprojectupdateattachment',
            name='daily_project_update',
        ),
        migrations.AddField(
            model_name='dailyprojectupdateattachment',
            name='daily_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.dailyprojectupdate', verbose_name='Daily Project Update'),
        ),
    ]
