# Generated by Django 3.2.8 on 2023-04-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0096_auto_20230406_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprojectupdatehistory',
            old_name='daily_project_update_hours',
            new_name='daily_update',
        ),
    ]
