# Generated by Django 3.2.8 on 2023-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0097_rename_daily_project_update_hours_dailyprojectupdatehistory_daily_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprojectupdate',
            name='note',
            field=models.TextField(blank=True, help_text="Manager's note / remarks", null=True),
        ),
    ]
