# Generated by Django 3.2.8 on 2023-05-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0165_auto_20230525_1750'),
        ('project_management', '0098_dailyprojectupdate_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='manager',
            field=models.ForeignKey(help_text='Manager / Lead', limit_choices_to=models.Q(('active', True), models.Q(('manager', True), ('lead', True), _connector='OR')), on_delete=django.db.models.deletion.RESTRICT, related_name='dailyprojectupdate_manager', to='employee.employee'),
        ),
    ]
