# Generated by Django 3.2.8 on 2023-09-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0100_alter_projecthour_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProjectHourGroupByEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Employee Project Hour Group by Employee',
                'verbose_name_plural': 'Employee Project Hours Group by Employee',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project_management.employeeprojecthour',),
        ),
    ]
