# Generated by Django 3.2.8 on 2023-09-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0102_alter_employeeprojecthourgroupbyemployee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprojecthourgroupbyemployee',
            options={'verbose_name': 'Weekly Hours by Employee', 'verbose_name_plural': 'Weekly Hours by Employees'},
        ),
    ]
