# Generated by Django 3.2.8 on 2023-09-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0103_alter_employeeprojecthourgroupbyemployee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprojecthourgroupbyemployee',
            options={'verbose_name': 'Weekly Employee Hours', 'verbose_name_plural': 'Weekly Employee Hours'},
        ),
    ]
