# Generated by Django 3.2.8 on 2023-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0104_alter_employeeprojecthourgroupbyemployee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprojectupdate',
            name='updates_json',
            field=models.JSONField(null=True),
        ),
    ]
