# Generated by Django 3.2.8 on 2023-10-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0105_dailyprojectupdate_updates_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='updates_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
