# Generated by Django 3.2.8 on 2023-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0106_auto_20231010_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprojectupdate',
            name='update',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
