# Generated by Django 3.2.8 on 2023-10-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0107_alter_dailyprojectupdate_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
