# Generated by Django 3.2.8 on 2023-11-03 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0108_project_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
