# Generated by Django 3.2.8 on 2023-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0109_alter_project_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_team',
            field=models.BooleanField(default=False, verbose_name='Is Team?'),
        ),
    ]
