# Generated by Django 3.2.8 on 2023-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0111_projectreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emergency_operation',
            field=models.BooleanField(default=False),
        ),
    ]
