# Generated by Django 3.2.8 on 2023-11-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0112_project_emergency_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreport',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='type',
            field=models.CharField(choices=[('manager', 'Manager'), ('lead', 'Lead'), ('sqa', 'SQA')], default='manager', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='project',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='project_management.project'),
        ),
    ]
