# Generated by Django 3.2.8 on 2023-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0113_auto_20231127_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('lead', 'Lead'), ('sqa', 'SQA')], default='manager', max_length=10),
        ),
    ]
