# Generated by Django 3.2.8 on 2023-12-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0115_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprojectupdate',
            options={'permissions': [('see_all_employee_update', 'Can see all daily update')], 'verbose_name': 'Daily Project Update', 'verbose_name_plural': 'Daily Project Updates'},
        ),
        migrations.AlterModelOptions(
            name='employeeprojecthour',
            options={'permissions': [('change_recent_activity', 'Can change if inserted recently (3days)'), ('see_all_employee_hour', 'Can see all emploployee project hour')], 'verbose_name': 'Employee Project Hour', 'verbose_name_plural': 'Employee Project Hours'},
        ),
        migrations.AlterModelOptions(
            name='projectreport',
            options={'verbose_name': 'Project Report', 'verbose_name_plural': 'Project Reports'},
        ),
    ]
