# Generated by Django 3.2.8 on 2023-12-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0116_auto_20231204_1458'),
        ('project_management', '0116_auto_20231207_1553'),
    ]

    operations = [
    ]
