# Generated by Django 3.2.8 on 2024-02-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0118_alter_dailyprojectupdate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_management_observationproject_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_projects', to='project_management.project')),
            ],
            options={
                'verbose_name': 'Observe New Projects',
            },
        ),
    ]
