# Generated by Django 3.2.8 on 2024-02-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0119_enabledailyupdatenow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enabledailyupdatenow',
            options={'verbose_name': 'Project Update Enable', 'verbose_name_plural': 'Project Update Enable by me'},
        ),
    ]
