# Generated by Django 3.2.8 on 2024-02-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0119_observationproject'),
        ('project_management', '0121_auto_20240229_1537'),
    ]

    operations = [
    ]
