# Generated by Django 3.2.8 on 2024-03-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0122_merge_0119_observationproject_0121_auto_20240229_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationproject',
            options={'verbose_name': 'Observe New Project'},
        ),
    ]
