# Generated by Django 3.2.8 on 2024-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0123_alter_observationproject_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthour',
            name='cto_feedback',
        ),
        migrations.AddField(
            model_name='projecthour',
            name='client_exp_feedback',
            field=models.URLField(blank=True, null=True, verbose_name='Client Experience Feedback'),
        ),
        migrations.AddField(
            model_name='projecthour',
            name='operation_feedback',
            field=models.URLField(blank=True, null=True, verbose_name='Operation Feedback'),
        ),
    ]
