# Generated by Django 3.2.8 on 2024-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0124_auto_20240313_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activate_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
