# Generated by Django 3.2.8 on 2024-05-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0125_auto_20240509_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': [('can see all project field', 'Can See All Project Field')]},
        ),
    ]
