# Generated by Django 3.2.8 on 2024-03-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0126_auto_20240314_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_design',
        ),
        migrations.DeleteModel(
            name='ProjectDesign',
        ),
    ]
