# Generated by Django 3.2.8 on 2024-05-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0126_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': [('can_see_all_project_field', 'Can See All Project Field')]},
        ),
    ]
