# Generated by Django 3.2.8 on 2024-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0127_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cc_email',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses for CC', null=True),
        ),
    ]
