# Generated by Django 3.2.8 on 2024-03-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0128_alter_project_project_key_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_challenges',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.projectchallenges'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_key_feature',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.projectkeyfeature'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_overview',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.projectoverview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_solution',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.projectsolution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_statement',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.projectstatement'),
        ),
    ]
