# Generated by Django 3.2.8 on 2024-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0129_auto_20240318_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_key_feature',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_overview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_solution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_statement',
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
