# Generated by Django 3.2.8 on 2024-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0130_auto_20240319_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='project_management.Tag'),
        ),
    ]
