# Generated by Django 3.2.8 on 2024-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0131_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_highlight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
