# Generated by Django 3.2.8 on 2024-03-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0133_auto_20240327_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('increased_sales', models.CharField(max_length=20)),
                ('return_on_investment', models.CharField(max_length=10)),
                ('increased_order_rate', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_results',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project_management.projectresults'),
        ),
    ]
