# Generated by Django 3.2.8 on 2024-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0134_auto_20240327_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_highlight',
            field=models.BooleanField(default=True),
        ),
    ]
