# Generated by Django 3.2.8 on 2024-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0135_alter_project_is_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
