# Generated by Django 3.2.8 on 2024-04-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0137_ourtechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectkeyfeature',
            name='project',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectkeyfeature',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
