# Generated by Django 3.2.8 on 2024-04-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0139_client_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_meta_info',
        ),
        migrations.DeleteModel(
            name='ProjectMetaInfo',
        ),
    ]
