# Generated by Django 3.2.8 on 2024-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0141_auto_20240430_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='industries',
            field=models.ManyToManyField(related_name='projects', to='project_management.ProjectIndustry'),
        ),
        migrations.AddField(
            model_name='project',
            name='platforms',
            field=models.ManyToManyField(related_name='projects', to='project_management.ProjectPlatform'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(related_name='projects', to='project_management.ProjectService'),
        ),
    ]
