# Generated by Django 3.2.8 on 2024-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0142_auto_20240506_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='industries',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='project_management.ProjectIndustry'),
        ),
        migrations.AlterField(
            model_name='project',
            name='platforms',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='project_management.ProjectPlatform'),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='project_management.ProjectService'),
        ),
    ]
