# Generated by Django 3.2.8 on 2024-05-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0127_alter_project_options'),
        ('project_management', '0144_auto_20240513_1409'),
    ]

    operations = [
    ]
