# Generated by Django 3.2.8 on 2024-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0145_merge_20240522_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='projectkeyfeature',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
