# Generated by Django 3.2.8 on 2024-06-07 20:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0146_auto_20240604_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_feedback',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
