# Generated by Django 3.2.8 on 2024-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0147_client_client_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
