# Generated by Django 3.2.8 on 2024-06-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0128_client_cc_email'),
        ('project_management', '0148_alter_client_client_feedback'),
    ]

    operations = [
    ]
