# Generated by Django 3.2.8 on 2024-06-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0149_merge_20240611_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='video_url',
            new_name='featured_video',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_note',
        ),
    ]
