# Generated by Django 3.2.4 on 2021-06-17 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 23, 15, 516544, tzinfo=utc)),
        ),
    ]
