# Generated by Django 3.2.5 on 2021-07-06 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='festival_bonus',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='festival_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='leave_bonus',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='project_bonus',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 6, 52, 6, 984190, tzinfo=utc)),
        ),
    ]
