# Generated by Django 3.2.5 on 2021-07-06 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0064_auto_20210706_1617'),
        ('account', '0042_auto_20210706_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 10, 17, 39, 183289, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='salarydisbursement',
            name='employee',
        ),
        migrations.AddField(
            model_name='salarydisbursement',
            name='employee',
            field=models.ManyToManyField(to='employee.Employee'),
        ),
    ]
