# Generated by Django 3.2.5 on 2021-07-06 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20210706_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydisbursement',
            name='default',
        ),
        migrations.AddField(
            model_name='salarydisbursement',
            name='disbursement_type',
            field=models.CharField(choices=[('salary_account', 'Salary Account'), ('personal_account', 'Personal Account')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 10, 41, 30, 813004, tzinfo=utc)),
        ),
    ]
