# Generated by Django 3.2.5 on 2021-07-09 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20210709_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 5, 58, 53, 279236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 5, 58, 53, 279736, tzinfo=utc)),
        ),
    ]
