# Generated by Django 3.2.5 on 2021-07-09 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20210709_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 0, 34, 182262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 0, 34, 182795, tzinfo=utc)),
        ),
    ]
