# Generated by Django 3.2.5 on 2021-07-12 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20210709_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='approved', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 8, 29, 13, 211389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 8, 29, 13, 211908, tzinfo=utc)),
        ),
    ]
