# Generated by Django 3.2.5 on 2021-07-12 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20210712_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 12, 27, 19, 974947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 12, 27, 19, 975426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='hour_rate',
            field=models.FloatField(default=10.0),
        ),
    ]
