# Generated by Django 3.2.5 on 2021-07-12 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_alter_employeeprojecthour_options'),
        ('account', '0056_auto_20210712_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 12, 32, 26, 404452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 12, 32, 26, 404900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='project',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, to='project_management.project'),
        ),
    ]
