# Generated by Django 3.2.5 on 2021-07-14 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_auto_20210712_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 7, 31, 15, 461442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 7, 31, 15, 461896, tzinfo=utc)),
        ),
    ]
