# Generated by Django 3.2.5 on 2021-07-14 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20210714_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 7, 32, 42, 440199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 14, 7, 32, 42, 440667, tzinfo=utc)),
        ),
    ]
