# Generated by Django 3.2.5 on 2021-07-19 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_auto_20210719_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 10, 14, 13, 75977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 10, 14, 13, 76970, tzinfo=utc)),
        ),
    ]
