# Generated by Django 3.2.6 on 2021-08-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_expensegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expanse_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='account.expensegroup'),
            preserve_default=False,
        ),
    ]
