# Generated by Django 3.2.6 on 2021-09-29 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0094_employee_national_id_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0072_profitshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.FloatField(help_text='Load amount')),
                ('emi', models.FloatField(help_text='Installment amount', verbose_name='EMI')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenor', models.IntegerField(help_text='Period month')),
                ('payment_method', models.CharField(choices=[('salary', 'Bank/Cash/Salary')], max_length=50)),
                ('loan_type', models.CharField(choices=[('salary', 'Salary Against Loan'), ('security', 'Security Loan'), ('collateral', 'Collateral Loan')], max_length=50)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_loan_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.employee')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='witness', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_amount', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_loanpayment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('national_id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_loanguarantor_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_loanattachment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
