# Generated by Django 3.2.5 on 2021-09-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0094_employee_national_id_no'),
        ('account', '0073_loan_loanattachment_loanguarantor_loanpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='witness',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='witness', to='employee.employee'),
        ),
    ]
