# Generated by Django 3.2.5 on 2021-10-01 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_employeesalary_loan_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
