# Generated by Django 3.2.8 on 2021-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_invoice_invoicedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='rate_of_supplementary_duty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='value_of_supplementary_duty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
