# Generated by Django 3.2.8 on 2021-11-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_auto_20211119_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
