# Generated by Django 3.2.8 on 2021-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_alter_invoice_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
