# Generated by Django 4.0.2 on 2022-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_alter_expanseattachment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitshare',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
