# Generated by Django 4.0.2 on 2022-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_profitshare_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='convert_rate',
            field=models.FloatField(default=80.0, help_text='BDT convert rate'),
        ),
    ]
