# Generated by Django 4.0.2 on 2022-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_income_convert_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='loss_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='convert_rate',
            field=models.FloatField(default=90.0, help_text='BDT convert rate'),
        ),
    ]
