# Generated by Django 4.0.2 on 2022-09-20 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_projectcommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcommission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
