# Generated by Django 4.0.2 on 2022-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_alter_projectcommission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='food_allowance',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
