# Generated by Django 3.2.8 on 2023-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_employeesalary_food_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='provident_fund',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
