# Generated by Django 3.2.8 on 2023-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_employeesalary_provident_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='code_quality_bonus',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
