# Generated by Django 3.2.8 on 2023-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_employeesalary_code_quality_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
