# Generated by Django 3.2.8 on 2023-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_employeefestivalbonus_festivalbonussheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='device_allowance',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
