# Generated by Django 3.2.8 on 2023-09-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_employeesalary_device_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('salary', 'Salary Against Loan'), ('tds', 'Tax Deduction at Source'), ('security', 'Security Loan'), ('collateral', 'Collateral Loan')], max_length=50),
        ),
    ]
