# Generated by Django 3.2.8 on 2023-12-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarysheet',
            options={'verbose_name': 'Salary Sheet', 'verbose_name_plural': 'Salary Sheets'},
        ),
    ]
