# Generated by Django 3.2.8 on 2024-01-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_alter_salarysheet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'permissions': (('can_approve_expense', 'Can Approve Expense'), ('can_view_all_expenses', 'Can View All Expenses'))},
        ),
    ]
