# Generated by Django 3.2.8 on 2024-01-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='account_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
