# Generated by Django 3.2.8 on 2024-01-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_accountjournal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountjournal',
            name='expense_groups',
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='expense_groups',
            field=models.ManyToManyField(related_name='expense_groups', to='account.ExpenseGroup'),
        ),
        migrations.RemoveField(
            model_name='accountjournal',
            name='expenses',
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='expenses',
            field=models.ManyToManyField(related_name='expenses', to='account.Expense'),
        ),
    ]
