# Generated by Django 3.2.8 on 2024-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0102_auto_20240118_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountjournal',
            name='pv_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
