# Generated by Django 3.2.8 on 2024-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_accountjournal_pv_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountjournal',
            name='type',
            field=models.CharField(choices=[('monthly', 'MONTHLY'), ('daily', 'DAILY')], max_length=20),
        ),
    ]
