# Generated by Django 3.2.8 on 2024-01-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0104_alter_accountjournal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountjournal',
            name='expense_groups',
        ),
    ]
