# Generated by Django 3.2.8 on 2024-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0108_accountjournal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountjournal',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
