# Generated by Django 3.2.8 on 2024-01-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0110_alter_accountjournal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountjournal',
            name='date',
        ),
    ]
