# Generated by Django 3.2.8 on 2024-01-23 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0111_remove_accountjournal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountjournal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
