# Generated by Django 3.2.8 on 2024-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_accountjournal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountjournal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
