# Generated by Django 3.2.8 on 2024-01-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0113_accountjournal_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentVoucher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accountjournal',),
        ),
    ]
