# Generated by Django 3.2.8 on 2024-02-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0115_auto_20240131_1740'),
        ('account', '0115_auto_20240131_1820'),
    ]

    operations = [
    ]
