# Generated by Django 3.2.8 on 2024-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0118_auto_20240311_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='add_to_balance_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='add_to_balance_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
