# Generated by Django 3.2.8 on 2024-03-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0119_auto_20240311_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='add_to_balance_sheet',
            field=models.BooleanField(default=True),
        ),
    ]
