# Generated by Django 3.2.8 on 2024-05-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_auto_20240513_1409'),
        ('account', '0121_auto_20240514_1441'),
    ]

    operations = [
    ]
