# Generated by Django 3.2.8 on 2024-05-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0122_merge_0121_auto_20240513_1409_0121_auto_20240514_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysheettaxloan',
            name='salarysheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salarysheet'),
        ),
    ]
