# Generated by Django 3.2 on 2021-04-29 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.designation')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.leave')),
                ('pay_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.payscale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
