# Generated by Django 3.2 on 2021-04-29 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(help_text='*.PDF file only', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default=55, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=55, help_text='Use (,) comma for separate phone numbers', max_length=60),
            preserve_default=False,
        ),
    ]
