# Generated by Django 3.2 on 2021-06-09 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pay_scale',
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.date(2021, 6, 9)),
        ),
    ]
