# Generated by Django 3.2 on 2021-06-09 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210609_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payable_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 9, 12, 58, 24, 472172, tzinfo=utc)),
        ),
    ]
