# Generated by Django 3.2 on 2021-06-09 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210609_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 9, 14, 22, 24, 281601, tzinfo=utc)),
        ),
    ]
