# Generated by Django 3.2 on 2021-06-11 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20210611_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemanagement',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✔ Approved'), ('rejected', '⛔ Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 11, 16, 15, 556575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 11, 16, 15, 557146, tzinfo=utc)),
        ),
    ]
