# Generated by Django 3.2 on 2021-06-11 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20210611_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemanagement',
            old_name='approved_at',
            new_name='status_changed_at',
        ),
        migrations.RenameField(
            model_name='leavemanagement',
            old_name='approve_by',
            new_name='status_changed_by',
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 11, 19, 56, 203810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 11, 19, 56, 204406, tzinfo=utc)),
        ),
    ]
