# Generated by Django 3.2 on 2021-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20210611_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_leave', models.FloatField()),
                ('message', models.TextField()),
                ('note', models.TextField(null=True)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('non_paid', 'Non Paid Leave')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✔ Approved'), ('rejected', '⛔ Rejected')], default='pending', max_length=20)),
                ('status_changed_at', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='leavemanagement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leavemanagement',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavemanagement',
            name='status_changed_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave',
        ),
    ]
