# Generated by Django 3.2 on 2021-06-11 13:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0005_auto_20210611_1952'),
        ('employee', '0023_auto_20210611_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_management',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.leavemanagement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leave_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='status_changed_by',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 13, 55, 48, 70081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaveattachment',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leave'),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 13, 55, 48, 70678, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LeaveManagement',
        ),
    ]
