# Generated by Django 3.2.4 on 2021-06-22 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_auto_20210618_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '👍 Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 22, 13, 43, 37, 967493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 22, 13, 43, 37, 970040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'user__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 6, 22, 13, 43, 37, 968100, tzinfo=utc)),
        ),
    ]
