# Generated by Django 3.2.4 on 2021-06-26 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_auto_20210622_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 5, 2, 9, 399419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('pending', '⌛ Pending'), ('approved', '👍 Approved'), ('rejected', '⛔ Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 5, 2, 9, 402411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 5, 2, 9, 400417, tzinfo=utc)),
        ),
    ]
