# Generated by Django 3.2.5 on 2021-07-02 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0049_auto_20210629_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permanent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 6, 24, 36, 26366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 6, 24, 36, 29116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 6, 24, 36, 27080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
