# Generated by Django 3.2.5 on 2021-07-02 13:44

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import employee.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_auto_20210702_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='*.pdf, *.doc, *.png, *.jpeg', upload_to=employee.models.attachment.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 44, 27, 317759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 44, 27, 321377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 44, 27, 318551, tzinfo=utc)),
        ),
    ]
