# Generated by Django 3.2.5 on 2021-07-02 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0054_auto_20210702_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 44, 37, 701224, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 44, 37, 705432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 44, 37, 701986, tzinfo=utc)),
        ),
    ]
