# Generated by Django 3.2.5 on 2021-07-06 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_publicholidaydate_public_holiday'),
        ('employee', '0056_auto_20210705_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='settings.payscale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='settings.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 7, 31, 55, 699454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='settings.leavemanagement'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 7, 31, 55, 703923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 7, 31, 55, 700206, tzinfo=utc)),
        ),
    ]
