# Generated by Django 3.2.5 on 2021-07-06 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_auto_20210706_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 9, 13, 12, 722844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 9, 13, 12, 727517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='active_from',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 9, 13, 12, 723650, tzinfo=utc)),
        ),
    ]
