# Generated by Django 3.2.6 on 2021-09-28 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0092_employeeskill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(150)]),
        ),
    ]
