# Generated by Django 4.0 on 2022-01-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0096_employee_tax_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tax_info',
            field=models.CharField(blank=True, help_text='i.e: 59530389237, Circle–138, Zone-11, Dhaka', max_length=255, null=True),
        ),
    ]
