# Generated by Django 4.0.2 on 2022-03-30 20:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0098_employee_image_employee_list_order_employeesocial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontent',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
