# Generated by Django 4.0.2 on 2022-03-30 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0099_alter_employeecontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
