# Generated by Django 4.0.2 on 2022-03-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0100_employee_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='uuid',
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
