# Generated by Django 4.0.2 on 2022-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0103_alter_employee_list_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='show_in_web',
            field=models.BooleanField(default=True),
        ),
    ]
