# Generated by Django 4.0.2 on 2022-10-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0105_employeelunch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeelunch',
            options={'permissions': (('can_see_all_lunch', 'Can able to see all lunch'),)},
        ),
    ]
