# Generated by Django 4.1.3 on 2022-11-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0106_alter_employeelunch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
