# Generated by Django 4.0.2 on 2022-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0108_employeeattendance_employeeonline_employeebreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
