# Generated by Django 4.0.2 on 2022-12-01 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0109_alter_employeeattendance_exit_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeBreak',
            new_name='EmployeeActivity',
        ),
    ]
