# Generated by Django 4.0.2 on 2022-12-01 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0110_rename_employeebreak_employeeactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='entry_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 1, 21, 14, 43, 970652)),
        ),
    ]
