# Generated by Django 4.0.2 on 2022-12-01 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0111_alter_employeeattendance_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='entry_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
