# Generated by Django 4.0.2 on 2022-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0112_alter_employeeattendance_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
