# Generated by Django 4.1.4 on 2022-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0039_alter_projecthour_forcast'),
        ('employee', '0115_employeeproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeproject',
            name='project',
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='project_management.project'),
        ),
    ]
