# Generated by Django 4.1.4 on 2022-12-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0116_remove_employeeproject_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project_eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
