# Generated by Django 3.2.8 on 2022-12-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0117_employee_project_eligibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeelunch',
            options={'permissions': (('can_see_all_lunch', 'Can able to see all lunch'),), 'verbose_name': 'Employee detail', 'verbose_name_plural': 'Employee details'},
        ),
    ]
