# Generated by Django 3.2.8 on 2022-12-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0118_alter_employeelunch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday_image',
            field=models.ImageField(blank=True, null=True, upload_to='birthday_images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday_image_shown',
            field=models.BooleanField(default=False),
        ),
    ]
