# Generated by Django 3.2.8 on 2022-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0119_auto_20221213_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
