# Generated by Django 3.2.8 on 2022-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0121_employeefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeefeedback',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='environmental_rating',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='facilities_rating',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='learning_growing_rating',
            field=models.FloatField(default=3.5),
            preserve_default=False,
        ),
    ]
