# Generated by Django 3.2.8 on 2023-01-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0123_employeefeedback_boss_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefeedback',
            options={'permissions': (('can_see_employee_feedback_admin', 'Can able to see emloyee feedback admin'),)},
        ),
    ]
