# Generated by Django 3.2.8 on 2023-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0124_alter_employeefeedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_in_cash_eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
