# Generated by Django 3.2.8 on 2023-01-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0125_employee_leave_in_cash_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='show_in_attendance_list',
            field=models.BooleanField(default=True),
        ),
    ]
