# Generated by Django 3.2.8 on 2023-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0127_prayerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerinfo',
            name='num_of_waqt',
        ),
        migrations.AddField(
            model_name='prayerinfo',
            name='num_of_waqt_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prayerinfo',
            name='waqt_asr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerinfo',
            name='waqt_fajr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerinfo',
            name='waqt_isha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerinfo',
            name='waqt_maghrib',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerinfo',
            name='waqt_zuhr',
            field=models.BooleanField(default=False),
        ),
    ]
