# Generated by Django 3.2.8 on 2023-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0129_employeeactivity_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pf_eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
