# Generated by Django 3.2.8 on 2023-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0130_employee_pf_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeactivity',
            name='is_updated_by_bot',
            field=models.BooleanField(default=False),
        ),
    ]
