# Generated by Django 3.2.8 on 2023-02-24 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0133_tourallowance_tour_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAgainstEmployeeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=500)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commentagainstemployeefeedback_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeefeedback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
