# Generated by Django 3.2.8 on 2023-03-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0133_tourallowance_tour_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'),)},
        ),
    ]
