# Generated by Django 3.2.8 on 2023-02-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0134_excusenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excusenote',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
