# Generated by Django 3.2.8 on 2023-02-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0134_commentagainstemployeefeedback'),
        ('employee', '0134_excusenote'),
    ]

    operations = [
    ]
