# Generated by Django 3.2.8 on 2023-02-28 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0135_alter_excusenote_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcuseNoteAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(help_text='Image , PDF or Docx file ', upload_to='')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_excusenoteattachment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('excuse_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.excusenote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
