# Generated by Django 3.2.8 on 2023-03-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0135_merge_20230224_2049'),
        ('employee', '0136_excusenoteattachment'),
    ]

    operations = [
    ]
