# Generated by Django 3.2.8 on 2023-03-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0137_merge_20230301_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': (('can_approve_leave_applications', 'Can able to approve leave applications'),)},
        ),
    ]
