# Generated by Django 3.2.8 on 2023-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0138_alter_leave_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_bonus_amount', models.PositiveIntegerField(default=10, verbose_name='QC Bonus Ratio')),
            ],
        ),
    ]
