# Generated by Django 3.2.8 on 2023-03-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0134_alter_employee_options'),
        ('employee', '0139_config'),
    ]

    operations = [
    ]
