# Generated by Django 3.2.8 on 2023-03-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0140_favouritemenu'),
        ('employee', '0140_merge_0134_alter_employee_options_0139_config'),
    ]

    operations = [
    ]
