# Generated by Django 3.2.8 on 2023-03-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0142_config_skip_lunch_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentagainstemployeefeedback',
            options={'ordering': ('-created_at',)},
        ),
    ]
