# Generated by Django 3.2.8 on 2023-04-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0146_auto_20230406_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todo List'},
        ),
    ]
