# Generated by Django 3.2.8 on 2023-04-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0147_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=False)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employeefaq_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeFAQView',
            fields=[
            ],
            options={
                'verbose_name_plural': 'FAQ List',
                'permissions': (('employee_faqs_view', 'Can Employee FAQ list view.'),),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employeefaq',),
        ),
    ]
