# Generated by Django 3.2.8 on 2023-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0148_employeefaq_employeefaqview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pf_eligibility',
            field=models.BooleanField(default=False),
        ),
    ]
