# Generated by Django 3.2.8 on 2023-04-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0149_alter_employee_pf_eligibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefaq',
            options={'verbose_name': 'Set FAQ', 'verbose_name_plural': 'Set FAQ'},
        ),
    ]
