# Generated by Django 3.2.8 on 2023-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0151_alter_employeefaq_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='cto_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
