# Generated by Django 3.2.8 on 2023-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0152_config_cto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='need_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
