# Generated by Django 3.2.8 on 2023-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0154_alter_config_cto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='cto_email',
            field=models.TextField(null=True, verbose_name='Alert Emails'),
        ),
    ]
