# Generated by Django 3.2.8 on 2023-05-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0156_alter_employeefaqview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('non_paid', 'Non Paid Leave'), ('half_day', 'Half Day Leave')], max_length=20),
        ),
    ]
