# Generated by Django 3.2.8 on 2023-05-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0157_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefaq',
            options={'permissions': (('can_approve_faq', 'Can approve FAQ'),), 'verbose_name': 'Set FAQ', 'verbose_name_plural': 'Set FAQ'},
        ),
    ]
