# Generated by Django 3.2.8 on 2023-05-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0158_alter_employeefaq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefaq',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
