# Generated by Django 3.2.8 on 2023-05-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0159_alter_employeefaq_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='need_at',
            new_name='need_cto_at',
        ),
    ]
