# Generated by Django 3.2.8 on 2023-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0160_rename_need_at_employee_need_cto_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='need_hr',
            field=models.BooleanField(default=False, verbose_name='I need help from HR'),
        ),
        migrations.AddField(
            model_name='employee',
            name='need_hr_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
