# Generated by Django 3.2.8 on 2023-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0161_auto_20230518_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='hr_email',
            field=models.TextField(null=True, verbose_name='HR Alert Emails'),
        ),
        migrations.AlterField(
            model_name='config',
            name='cto_email',
            field=models.TextField(null=True, verbose_name='CTO Alert Emails'),
        ),
    ]
