# Generated by Django 3.2.8 on 2023-05-23 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0162_auto_20230518_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(null=True)),
                ('asigned_by', models.ForeignKey(limit_choices_to={'active': True, 'manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='skill_acquisition_asigned_by', to='employee.employee')),
                ('asigned_to', models.ForeignKey(limit_choices_to={'active': True, 'project_eligibility': True}, on_delete=django.db.models.deletion.CASCADE, related_name='skill_acquisition_asigned_to', to='employee.employee')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_learning_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
