# Generated by Django 3.2.8 on 2023-05-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0164_employee_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='asigned_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('active', True), models.Q(('manager', True), ('lead', True), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='learning_by', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='asigned_to',
            field=models.ForeignKey(limit_choices_to={'active': True, 'project_eligibility': True}, on_delete=django.db.models.deletion.CASCADE, related_name='learning_to', to='employee.employee'),
        ),
    ]
