# Generated by Django 3.2.8 on 2023-06-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0165_auto_20230525_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeelunch',
            options={'permissions': (('can_see_all_lunch', 'Can able to see all lunch'),), 'verbose_name': 'Employee List', 'verbose_name_plural': 'Employee List'},
        ),
    ]
