# Generated by Django 3.2.8 on 2023-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0167_auto_20230619_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
