# Generated by Django 3.2.8 on 2023-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0168_alter_bankaccount_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='festival_bonus_eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
