# Generated by Django 3.2.8 on 2023-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0169_employee_festival_bonus_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_allowance',
            field=models.BooleanField(default=False),
        ),
    ]
