# Generated by Django 3.2.8 on 2023-08-11 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0171_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Date of Home Office Start')),
                ('end_date', models.DateField(help_text='Date of Home Office End')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(120)])),
                ('total_day', models.FloatField()),
                ('note', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✔ Approved'), ('rejected', '⛔ Rejected')], default='pending', max_length=20)),
                ('status_changed_at', models.DateField(null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_homeoffice_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('status_changed_by', models.ForeignKey(limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_approve_homeoffice_application', 'Can Approve Home Office Application'),),
            },
        ),
        migrations.CreateModel(
            name='HomeOfficeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(help_text='Image , PDF or Docx file', upload_to='')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_homeofficeattachment_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('homeoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.homeoffice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
