# Generated by Django 3.2.8 on 2023-08-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0172_homeoffice_homeofficeattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excusenote',
            options={'verbose_name': 'HR Report note', 'verbose_name_plural': 'HR Report notes'},
        ),
        migrations.CreateModel(
            name='HRReportNoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_hrreportnotecategory_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'HR Report Note Category',
                'verbose_name_plural': 'HR Report Note Categories',
            },
        ),
        migrations.AddField(
            model_name='excusenote',
            name='category',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.hrreportnotecategory'),
        ),
    ]
