# Generated by Django 3.2.8 on 2023-08-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0173_auto_20230824_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefaq',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
