# Generated by Django 3.2.8 on 2023-09-06 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0175_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_hrpolicy_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Set HR Policy',
                'verbose_name_plural': 'Set HR Policies',
            },
        ),
        migrations.CreateModel(
            name='HRPolicySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_hrpolicysection_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('hr_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.hrpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HRPolicyPublic',
            fields=[
            ],
            options={
                'verbose_name': 'HR Contract Policy',
                'verbose_name_plural': 'HR Contract Policies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.hrpolicy',),
        ),
    ]
