# Generated by Django 3.2.8 on 2023-09-13 14:35

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    enoc_model = apps.get_model("employee", "employeenoc")
    for enoc in enoc_model.objects.all():
        enoc.uuid = uuid.uuid4()
        enoc.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0178_alter_employeenoc_noc_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeenoc",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employeenoc",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                blank=False,
                null=False,
            ),
        ),
    ]
