# Generated by Django 3.2.8 on 2023-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0179_employeenoc_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeenoc',
            name='noc_image',
            field=models.ImageField(blank=True, null=True, upload_to='noc_images/'),
        ),
    ]
