# Generated by Django 3.2.8 on 2023-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0181_employeeneedhelp_needhelpposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeneedhelp',
            name='need_help_position',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='employee.NeedHelpPosition'),
        ),
    ]
