# Generated by Django 3.2.8 on 2023-11-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0183_auto_20231103_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✔ Approved'), ('rejected', '⛔ Rejected')], default='pending', max_length=20)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leave')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
