# Generated by Django 3.2.8 on 2023-11-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0184_leavemanagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavemanagement',
            options={'verbose_name': 'Leave Approval', 'verbose_name_plural': 'Leave Approvals'},
        ),
        migrations.AlterField(
            model_name='leavemanagement',
            name='manager',
            field=models.ForeignKey(limit_choices_to=models.Q(('active', True), models.Q(('manager', True), ('lead', True), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
