# Generated by Django 3.2.8 on 2023-11-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0186_auto_20231124_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Technology',
                'verbose_name_plural': 'Employee Technologies',
                'ordering': ('name', '-created_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'), ('can_access_all_employee', 'Can acccess all employee'))},
        ),
        migrations.CreateModel(
            name='EmployeeExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance'), ('master', 'Master')], max_length=15)),
                ('employee', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeetechnology')),
            ],
            options={
                'verbose_name': 'Employee Expertise',
                'verbose_name_plural': 'Employee Expertises',
                'ordering': ('-created_at',),
            },
        ),
    ]
