# Generated by Django 3.2.8 on 2023-12-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0187_auto_20231130_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'), ('can_access_all_employee', 'Can acccess all employee'))},
        ),
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'verbose_name': 'Employee Attendance', 'verbose_name_plural': 'Employee Attendances'},
        ),
        migrations.AlterModelOptions(
            name='excusenote',
            options={'verbose_name': 'HR Report Note', 'verbose_name_plural': 'HR Report Notes'},
        ),
        migrations.AlterModelOptions(
            name='favouritemenu',
            options={'verbose_name': 'Favourite Menu', 'verbose_name_plural': 'Favourite Menus'},
        ),
    ]
