# Generated by Django 3.2.8 on 2023-12-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0188_auto_20231201_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'), ('can_access_all_employee', 'Can acccess all employee'))},
        ),
    ]
