# Generated by Django 3.2.8 on 2023-12-04 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0189_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexpertise',
            name='level',
        ),
        migrations.RemoveField(
            model_name='employeeexpertise',
            name='technology',
        ),
        migrations.AddField(
            model_name='employeetechnology',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeexpertise',
            name='employee',
            field=models.OneToOneField(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeExpertTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance'), ('master', 'Master')], max_length=15)),
                ('percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('technology', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employeetechnology')),
            ],
            options={
                'verbose_name': 'Employee Expertise Level',
                'verbose_name_plural': 'Employee Expertise Levels',
                'ordering': ('technology__name',),
            },
        ),
        migrations.AddField(
            model_name='employeeexpertise',
            name='technology_level',
            field=models.ManyToManyField(related_name='technology_level', to='employee.EmployeeExpertTech'),
        ),
    ]
