# Generated by Django 3.2.8 on 2023-12-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0191_auto_20231204_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexpertise',
            name='technology_level',
        ),
        migrations.AddField(
            model_name='employeeexperttech',
            name='employee_expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_expertise', to='employee.employeeexpertise'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeexperttech',
            unique_together=set(),
        ),
    ]
