# Generated by Django 3.2.8 on 2023-12-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0192_auto_20231204_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperttech',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('master', 'Master')], max_length=15),
        ),
    ]
