# Generated by Django 3.2.8 on 2023-12-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0193_alter_employeeexperttech_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='entry_pass_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
