# Generated by Django 3.2.8 on 2024-01-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0194_employee_entry_pass_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'permissions': [('can_approve_overtime', 'Can Approve Overtime')]},
        ),
    ]
