# Generated by Django 3.2.8 on 2024-01-04 15:23

from django.db import migrations, models
import employee.models.employee


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0195_alter_overtime_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
