# Generated by Django 3.2.8 on 2024-01-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0196_employee_display_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='display_id',
        ),
    ]
