# Generated by Django 3.2.8 on 2024-01-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0199_employeerating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'permissions': (('can_see_formal_summery_view', 'Can able to see emloyee summary view'), ('can_access_all_employee', 'Can acccess all employee'), ('can_access_average_rating', 'Can access average rating of Employee.'))},
        ),
    ]
