# Generated by Django 3.2.8 on 2024-01-15 16:06.m.


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0201_auto_20240111_2052'),
        # ('employee', '0201_employeerating_project'),
    ]

    operations = [
    ]
