# Generated by Django 3.2.8 on 2024-01-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0201_employeerating_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOAppointmentModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
    ]
