# Generated by Django 3.2.8 on 2024-01-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0202_ceoappointmentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceoappointmentmodel',
            options={'verbose_name': 'CEO Appointment', 'verbose_name_plural': 'CEO Appointment List'},
        ),
    ]
