# Generated by Django 3.2.8 on 2024-01-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0202_merge_20240115_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': (('can_approve_leave_applications', 'Can able to approve leave applications'), ('can_add_leave_at_any_time', 'Can able to add leave at any time'))},
        ),
    ]
