# Generated by Django 3.2.8 on 2024-01-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0202_merge_20240115_1621'),
        ('employee', '0203_alter_leave_options'),
    ]

    operations = [
    ]
