# Generated by Django 3.2.8 on 2024-01-16 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0117_merge_0116_auto_20231204_1458_0116_auto_20231207_1553'),
        ('employee', '0203_alter_ceoappointmentmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEOAppointmentModel',
        ),
        migrations.CreateModel(
            name='CEOAppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_time', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ceoappointmentmodel_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project')),
            ],
            options={
                'verbose_name': 'CEO Appointment',
                'verbose_name_plural': 'CEO Appointment List',
            },
        ),
    ]
