# Generated by Django 3.2.8 on 2024-01-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0204_merge_20240116_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemanagement',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '⛔ Rejected'), ('need_action', '🤔 Need Further Discussion')], default='pending', max_length=20),
        ),
    ]
