# Generated by Django 3.2.8 on 2024-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0204_auto_20240116_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceoappointmentmodel',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='ceoappointmentmodel',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='ceoappointmentmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ceoappointmentmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='ceoappointmentmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
