# Generated by Django 3.2.8 on 2024-01-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0205_auto_20240116_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEOAppointmentModel',
        ),
    ]
