# Generated by Django 3.2.8 on 2024-01-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0117_merge_0116_auto_20231204_1458_0116_auto_20231207_1553'),
        ('employee', '0207_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
