# Generated by Django 3.2.8 on 2024-01-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0205_alter_leavemanagement_status'),
        ('employee', '0208_auto_20240117_1321'),
    ]

    operations = [
    ]
