# Generated by Django 3.2.8 on 2024-01-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0209_merge_20240117_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerating',
            options={'permissions': [('can_view_all_ratings', 'Can View All Ratings Provided')], 'verbose_name': 'Employee Rating', 'verbose_name_plural': 'Employee Ratings'},
        ),
    ]
