# Generated by Django 3.2.8 on 2024-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0210_alter_employeerating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpolicy',
            name='policy_file',
            field=models.FileField(default='src/medea/Screenshot_from_2024-01-12_11-54-44_tnpmMqi.png', upload_to='src/media/'),
        ),
    ]
