# Generated by Django 3.2.8 on 2024-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0212_alter_hrpolicy_policy_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrpolicy',
            name='policy_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
