# Generated by Django 3.2.8 on 2024-02-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0117_merge_0116_auto_20231204_1458_0116_auto_20231207_1553'),
        ('employee', '0214_alter_hrpolicy_policy_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeerating',
            name='project',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project'),
        ),
    ]
