# Generated by Django 3.2.8 on 2024-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0216_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '⛔ Rejected'), ('need_discussion', '🤔 Need Discussion')], default='pending', max_length=20),
        ),
    ]
