# Generated by Django 3.2.8 on 2024-02-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_alter_employeefoodallowance_options'),
        ('employee', '0217_alter_leave_status'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='bankaccount',
        #     unique_together={('employee', 'bank')},
        # ),
    ]
