# Generated by Django 3.2.8 on 2024-02-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0218_alter_bankaccount_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
    ]
