# Generated by Django 3.2.8 on 2024-02-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0219_alter_bankaccount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
