# Generated by Django 3.2.8 on 2024-02-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0220_alter_bankaccount_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
