# Generated by Django 3.2.8 on 2024-02-06 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0220_alter_bankaccount_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leavefeedback_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leave')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
