# Generated by Django 3.2.8 on 2024-02-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_alter_employeefoodallowance_options'),
        ('employee', '0222_alter_bankaccount_employee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('employee', 'bank')},
        ),
    ]
