# Generated by Django 3.2.8 on 2024-02-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0222_alter_leave_options'),
        ('employee', '0223_alter_bankaccount_unique_together'),
    ]

    operations = [
    ]
