# Generated by Django 3.2.8 on 2024-02-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0224_merge_20240207_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': (('can_approve_leave_applications', 'Can able to approve leave applications'), ('can_add_leave_at_any_time', 'Can able to add leave at any time'))},
        ),
        migrations.AlterModelOptions(
            name='leavefeedback',
            options={'verbose_name': 'Management Feedback', 'verbose_name_plural': 'Management Feedbacks'},
        ),
    ]
