# Generated by Django 3.2.8 on 2024-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0225_auto_20240208_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sql',
            field=models.BooleanField(default=False),
        ),
    ]
