# Generated by Django 3.2.8 on 2024-02-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0226_employee_sql'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sql',
            new_name='sqa',
        ),
    ]
