# Generated by Django 3.2.8 on 2024-02-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0225_auto_20240208_1313'),
        ('employee', '0227_rename_sql_employee_sqa'),
    ]

    operations = [
    ]
