# Generated by Django 3.2.8 on 2024-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0228_auto_20240209_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='score',
            field=models.FloatField(),
        ),
    ]
