# Generated by Django 3.2.8 on 2024-02-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0228_merge_20240213_2016'),
        ('employee', '0229_alter_employeerating_score'),
    ]

    operations = [
    ]
