# Generated by Django 3.2.8 on 2024-02-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0231_alter_resignation_employee'),
        ('employee', '0231_observation'),
    ]

    operations = [
    ]
