# Generated by Django 3.2.8 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0232_merge_20240229_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March')], default=3),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='year',
            field=models.IntegerField(choices=[(2023, 2023), (2024, 2024)], default=2024),
        ),
    ]
