# Generated by Django 3.2.8 on 2024-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0235_auto_20240305_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resignation',
            options={'permissions': (('can_view_all_resignations', 'Can View All Resignations'),)},
        ),
    ]
