# Generated by Django 3.2.8 on 2024-03-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0236_alter_resignation_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('employee',)},
        ),
    ]
