# Generated by Django 3.2.8 on 2024-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0238_alter_employeerating_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerating',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May')], default=5),
        ),
    ]
