# Generated by Django 3.2.8 on 2024-05-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0239_alter_employeerating_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
