# Generated by Django 3.2.8 on 2024-05-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0240_alter_employee_options'),
        ('employee', '0240_employee_tax_eligible'),
    ]

    operations = [
    ]
