# Generated by Django 3.2.8 on 2024-05-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0242_bookconferenceroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeproject'),
        ),
    ]
