# Generated by Django 3.2.8 on 2024-05-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0127_alter_project_options'),
        ('employee', '0243_alter_bookconferenceroom_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconferenceroom',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
