# Generated by Django 3.2.8 on 2024-06-14 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('employee', '0252_auto_20240613_1934'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='lateattendancefine',
        #     name='date',
        #     field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        # ),
    ]
