# Generated by Django 3.2.6 on 2021-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_alter_asset_sub_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sub_asset',
            field=models.ManyToManyField(blank=True, related_name='_asset_management_asset_sub_asset_+', to='asset_management.Asset'),
        ),
    ]
