# Generated by Django 3.2.6 on 2021-09-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_alter_asset_sub_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='sub_asset',
        ),
    ]
