# Generated by Django 4.0 on 2022-01-12 19:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0012_alter_credential_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
