# Generated by Django 4.0.2 on 2022-11-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0013_alter_credential_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'permissions': [('access_all_credentials', 'Can able to see all credentials')]},
        ),
    ]
