# Generated by Django 3.2.8 on 2023-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0014_alter_credential_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='active', max_length=15),
        ),
    ]
