# Generated by Django 3.2.8 on 2023-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0016_alter_credential_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '✔ Active'), ('INACTIVE', '✖ InActive')], default='Active', max_length=15),
        ),
    ]
