# Generated by Django 3.2.8 on 2023-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0018_auto_20230704_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
