# Generated by Django 3.2.8 on 2023-07-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0170_employee_device_allowance'),
        ('asset_management', '0019_alter_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignedasset',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='asset_management.asset'),
        ),
        migrations.AlterField(
            model_name='employeeassignedasset',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
