# Generated by Django 3.2.8 on 2023-08-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0172_homeoffice_homeofficeattachment'),
        ('asset_management', '0020_auto_20230705_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.AlterField(
            model_name='employeeassignedasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management.asset'),
        ),
    ]
